### ISSUE TITLE
Flipper isn't capturing any network activity from flutter_inappbrowser_example in iOS Simulator

### ISSUE THREAD

**Issue by mtchllbrrn** [leanflutter/flutter_flipperkit_examples#2]
I've successfully built/run the `flutter_inappbrowser_example` app in the iOS Simulator.  When I run the Flipper desktop app and connect to the running Simulator, I can see things printing in the Logs section.  However, the Network tab doesn't show any requests at all.

I've also tried Flutter Debugger, behavior is the same.

For what it's worth, I'm having an identical problem with my own project after configuring Flipper & the Networking plugin according to the documentation.

**Comment by lijy91** [comment]
@mtchllbrrn 

1. `flutter_inappbrowser_example` is just a demonstration of how to integrate `flutter_inappbrowser` plugin

2. This is a  bug in `flutter_flutterkit` 0.0.16, please upgrade to `flutter_flutterkit` 0.0.17.


I added a new example: https://github.com/blankapp/flutter_flipperkit_examples/tree/master/dio_example

**Comment by mtchllbrrn** [comment]
Thanks, the new dio example works as expected.  Unfortunately it hasn't solved the problem with my own project. I'll open a separate issue for that on the `flutter_flipperkit` repo.

**Comment by lijy91** [comment]
@mtchllbrrn Can you provide an example to reproduce your problem?

**Comment by mtchllbrrn** [comment]
The new issue is available here:

https://github.com/blankapp/flutter_flipperkit/issues/14
